spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/doctor_db
    username: postgres
    password: suhrob2008
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  banner:
    location: classpath:product-banner.txt
  mail:
    host: smtp.gmail.com
    port: 587
    username: qurbonmurodovsuhrob4@gmail.com
    password: 'thav mxox tqfb xjge'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
myapp:
  secret-key: 'c0388696-55b0-479c-a142-a2ae7cbe269a'

api:
  version: 1.0.0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html


google:
  recaptcha:
    secret: '6Le1rHErAAAAAPkBT_adGbtDbcjPhdeYGm7VTnZg'
    site: '6Le1rHErAAAAAH9f_A3JPoNt7Tbv8ejBFK9XlfcL'



